services:
  - type: web
    name: telegram-channel-marketplace
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: telegram-marketplace-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    healthCheckPath: /api/health

databases:
  - name: telegram-marketplace-db
    plan: free