services:
  - type: web
    name: telegram-channel-marketplace
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: DATABASE_URL
        sync: false
    autoDeploy: true